#! /bin/bash

# Simple script for DNS lookups. Exits zero if every ip address in the records
# for the domain passed as the second argument is exactly the same as the ip
# address passed as the first argument.

ip_address=$1;
domain=$2;

if [ -z $domain ]; then
	echo -e "Usage:\n  check-domain-resolution <ip address> <domain>"
	exit 255
fi

exit $(dig $2 +short 2>&1 | grep -E '[0-9]{1,3}\.' | grep -v $ip_address | wc -l)
