#! /bin/bash

# Simple script for DNS lookups. Exits zero if every ip address in the records
# for the domain passed as the second argument is exactly the same as the ip 
# address passed as the first argument.

ip_address=$1;
domain=$2;

if [ -z $domain ]; then
	echo -e "Usage:\n  check-domain-resolution <ip address> <domain>"
fi

dig $2 +short 2>&1 | grep -e "^[0-9]" | grep -qv $ip_address && exit 1

exit 0
